using Microsoft.EntityFrameworkCore;
using WexCorporatePayments.Domain.Entities;

namespace WexCorporatePayments.Infrastructure.Persistence;

/// <summary>
/// Database context using EF Core.
/// </summary>
public class AppDbContext : DbContext
{
    public DbSet<PurchaseTransaction> PurchaseTransactions { get; set; } = null!;

    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // PurchaseTransaction entity configuration
        modelBuilder.Entity<PurchaseTransaction>(entity =>
        {
            entity.ToTable("PurchaseTransactions");

            entity.HasKey(e => e.Id);

            entity.Property(e => e.Id)
                .IsRequired()
                .ValueGeneratedNever(); // Id is generated by the entity

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.TransactionDate)
                .IsRequired();

            entity.Property(e => e.AmountUsd)
                .IsRequired()
                .HasPrecision(18, 2);
        });
    }
}
